name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: nc_games_test
          postgresql user: 'test_user'
          postgresql password: 'test_password'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=nc_games_test PGUSER=test_user PGPASSWORD=test_password npm t

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.e18634a8-8304-4d34-8762-299ff8dde38e }}
          heroku_app_name: ${{ secrets.nc-board-quest }}
          heroku_email: ${{ secrets.jclleggett@gmail.com }}